apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xparents.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XParent
  resources:
  - name: child-resource
    base:
      apiVersion: nop.example.org/v1alpha1
      kind: XNopResource
      spec:
        coolField: "I'M COOL!"
